# vim: filetype=swayconfig

bar {
    swaybar_command waybar
}

# exec_always --no-startup-id  feh --no-fehbg --bg-fill '/home/jeanclaude/.config/feh/bg.jpg'
#exec --no-startup-id redshift -c ~/.config/redshift/redshift.conf
exec --no-startup-id dunst -config ~/.config/dunst/dunstrc
exec --no-startup-id xiccd
