# vim: filetype=swayconfig

#define BACKGROUND  #2d2d2d
#define FOREGROUND  #f3f4f5
#define CURSOR      #2d2d2d
set $color0   #2d2d2d
set $color8   #2f343f
set $color1   #f27777
set $color9   #f06666
set $color2   #99cc99
set $color10  #66aa66
set $color3   #ffcc66
set $color11  #ddaa55
set $color4   #6699cc
set $color12  #4488aa
set $color5   #cc99cc
set $color13  #bb80bb
set $color6   #6ccccc
set $color14  #5aaaaa
set $color7   #676E7D
set $color15  #f3f4f5
