# vim: filetype=swayconfig

font pango: Hack 10

# Remove Title Bar
default_border pixel 1
default_floating_border pixel 1

# window colors
#                       border      background  text        indicator
client.focused          $color8     $color4     $color15    $color8
client.unfocused        $color8     $color8     $color7     $color8
client.focused_inactive $color8     $color8     $color7     $color8
client.urgent           $color1     $color1     $color15    $color8

# Workspace Name
set $ws1 "1. "
set $ws2 "2. "
set $ws3 "3. "
set $ws4 "4"
set $ws5 "5"
set $ws6 "6 "
set $ws7 "7"
set $ws8 "8"
set $ws9 "9. "
set $ws10 "10. "
