#!/bin/sh

xrdb "$HOME/.config/X11/Xresources"

# Make sure pen stick the touchscreen
xinput --map-to-output 'Wacom Pen and multitouch sensor Finger touch' eDP-1
xinput --map-to-output 'Wacom Pen and multitouch sensor Pen stylus' eDP-1
xinput --map-to-output 'Wacom Pen and multitouch sensor Pen eraser' eDP-1

# Disable beep bell
xset -b

# Fix application starting super slow
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

exec i3
