version: '3.1'

services:
    letsencrypt:
        image: nginx:latest
        container_name: letsencrypt
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Site:/usr/share/nginx/html
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
