version: '3'
services:
    reverseproxy:
        image: nginx:latest
        container_name: reverseproxy
        volumes:
            # Config
            - ./ReverseProxy/conf.d:/etc/nginx/conf.d
            - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
            - ./ReverseProxy/ssl.conf:/etc/nginx/ssl.conf
            - ./ReverseProxy/common.conf:/etc/nginx/common.conf
            - ./ReverseProxy/common_location.conf:/etc/nginx/common_location.conf

            # DH
            - ./ReverseProxy/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem

            # SSL
            - /docker-volumes/etc/letsencrypt/live/www.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.jeanclaudegraf.ch/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/www.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.jeanclaudegraf.ch/privkey.pem

            - /docker-volumes/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/privkey.pem

           # Cert Bot
            - /docker-volumes/data/letsencrypt:/data/letsencrypt

        ports:
            - 80:80
            - 443:443
        networks:
            - reverseProxyNetwork

    testsite:
        image: httpd:latest
        container_name: testsite
        volumes:
            - ./TestSite:/usr/local/apache2/htdocs/
        ports:
            - 8080:8080
        networks:
            - reverseProxyNetwork

networks:
    reverseProxyNetwork:
