version: '3'
services:
    reverseproxy:
        image: nginx:latest
        container_name: reverseproxy
        volumes:

            # Config
            - ./ReverseProxy/conf.d:/etc/nginx/conf.d
            - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
            - ./ReverseProxy/ssl.conf:/etc/nginx/ssl.conf
            - ./ReverseProxy/common.conf:/etc/nginx/common.conf
            - ./ReverseProxy/common_location.conf:/etc/nginx/common_location.conf

            # DH
            - ./ReverseProxy/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem

            # SSL
            ## jeanclaudgraf.ch
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.jeanclaudegraf.ch/fullchain.pem
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.jeanclaudegraf.ch/privkey.pem

            ## test.jeanclaudegraf.ch
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/fullchain.pem
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.test.jeanclaudegraf.ch/privkey.pem

            ## git.jeanclaudegraf.ch
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.git.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.git.jeanclaudegraf.ch/fullchain.pem
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.git.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.git.jeanclaudegraf.ch/privkey.pem

            ## nc.jeanclaudegraf.ch
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.nc.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.nc.jeanclaudegraf.ch/fullchain.pem
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.nc.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.nc.jeanclaudegraf.ch/privkey.pem


            ## drone.jeanclaudegraf.ch
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.drone.jeanclaudegraf.ch/fullchain.pem:/etc/letsencrypt/live/www.drone.jeanclaudegraf.ch/fullchain.pem
            - /home/jeanclaude/HomeServer/Ssl/etc/letsencrypt/live/www.drone.jeanclaudegraf.ch/privkey.pem:/etc/letsencrypt/live/www.drone.jeanclaudegraf.ch/privkey.pem

           # Cert Bot
            - /home/jeanclaude/HomeServer/Ssl/data/letsencrypt:/data/letsencrypt

        networks:
            - ReverseProxy
        restart: always
        depends_on:
            - gitea
            - homepage-wp
            - nextcloud-web

# Test
    testsite:
        image: httpd:latest
        container_name: testsite
        volumes:
            - ./TestSite:/usr/local/apache2/htdocs/
        networks:
            - ReverseProxy

# Gitea
    gitea:
        image: gitea/gitea:1.11.0
        container_name: gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - DB_TYPE=mysql
            - DB_HOST=gitea-db:3306
            - DB_NAME=gitea
            - DB_USER=gitea
            - SSH_DOMAIN=git.jeanclaudegraf.ch:2222
            - DISABLE_REGISTRATION=true
            - ROOT_URL=https://www.git.jeanclaudegraf.ch
        env_file:
            - ./Gitea/gitea.env
        volumes:
            - gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "2222:22"
        networks:
            - ReverseProxy
            - Gitea
        depends_on:
            - gitea-db

    gitea-db:
        image: mysql:5.7
        container_name: gitea-db
        environment:
            - MYSQL_USER=gitea
            - MYSQL_DATABASE=gitea
        env_file:
            - ./Gitea/db.env
        volumes:
            - gitea-db:/var/lib/mysql
        command: --disable-partition-engine-check
        networks:
             - Gitea

    drone:
        image: drone/drone:latest
        container_name: drone
        environment:
#DRONE_CRON_DISABLED
#DRONE_CRON_INTERVAL
            - DRONE_GIT_ALWAYS_AUTH=true
#DRONE_GIT_PASSWORD
#DRONE_GIT_USERNAME
            - DRONE_GITEA_SERVER=https://www.git.jeanclaudegraf.ch
#            - DRONE_LOGS_DEBUG=true
#            - DRONE_LOGS_PRETTY=true
#DRONE_REGISTRATION_CLOSED
            - DRONE_SERVER_HOST=www.drone.jeanclaudegraf.ch
            - DRONE_SERVER_PROTO=https
            - DRONE_TLS_AUTOCERT=false
        env_file:
            - ./Drone/drone.env
        volumes:
            - drone:/data
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ReverseProxy
            - Gitea
            - Drone
        depends_on:
            - gitea

    drone-runner:
        image: drone/drone-runner-docker:latest
        container_name: drone-runner
        environment:
#            - DRONE_DEBUG=true
#DRONE_DOCKER_CONFIG
            - DRONE_RPC_HOST=www.drone.jeanclaudegraf.ch
            - DRONE_RPC_PROTO=https
            - DRONE_RUNNER_NAME=Drone-Runner
            - DRONE_RUNNER_NETWORKS=ReverseProxy
#DRONE_RUNNER_VOLUMES
#DRONE_UI_DISABLED
#DRONE_UI_REALM
        env_file:
            - ./Drone/runner.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ReverseProxy
            - Drone
        depends_on:
            - drone

# Wordpress Homepage
    homepage-wp:
        image: wordpress:latest
        container_name: homepage-wp
        environment:
            - WORDPRESS_DB_HOST=homepage-wp-db:3306
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_NAME=wordpress
        env_file:
            - ./Homepage/wp.env
        volumes:
            - homepage-wp-html:/var/www/html
            - ./Homepage/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - ReverseProxy
            - HomepageWp
        depends_on:
            - homepage-wp-db

    homepage-wp-db:
        image: mariadb:latest
        container_name: homepage-wp-db
        environment:
            - MYSQL_USER=wordpress
            - MYSQL_DATABASE=wordpress
        env_file:
            - ./Homepage/db.env
        volumes:
            - homepage-wp-db:/var/lib/mysql
        networks:
            - HomepageWp

# Nextcloud
    nextcloud:
        image: nextcloud:fpm-alpine
        container_name: nextcloud
        volumes:
            - nextcloud-html:/var/www/html
            - /mnt/nc/data:/srv/nextcloud/data
            - /mnt/nc/presents:/srv/nextcloud/presents
        environment:
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=nextcloud-db
            - NEXTCLOUD_DATA_DIR=/srv/nextcloud/data
        env_file:
            - ./Nextcloud/nc.env
        networks:
            - Nextcloud
        depends_on:
            - nextcloud-db

    nextcloud-db:
        image: mariadb
        container_name: nextcloud-db
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - nextcloud-db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        env_file:
            - ./Nextcloud/db.env
        networks:
            - Nextcloud

    nextcloud-web:
        build: ./Nextcloud/Web
        container_name: nextcloud-web
        volumes:
            - nextcloud-html:/var/www/html:ro
        networks:
            - ReverseProxy
            - Nextcloud
        depends_on:
            - nextcloud

networks:
    ReverseProxy:
    Gitea:
    Drone:
    HomepageWp:
    Nextcloud:

volumes:
    gitea:
        driver: local
    gitea-db:
        driver: local
    homepage-wp-html:
    homepage-wp-db:
    nextcloud-html:
    nextcloud-db:
    drone:
