version: '3'
services:
    reverseproxy:
        image: nginx:latest
        container_name: reverseproxy
        volumes:
            - ./ReverseProxy/conf.d:/etc/nginx/conf.d
            - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        networks:
            - reverseProxyNetwork

    testsite:
        image: httpd:latest
        container_name: testsite
        volumes:
            - ./TestSite:/usr/local/apache2/htdocs/
        ports:
            - 8080:8080
        networks:
            - reverseProxyNetwork

networks:
    reverseProxyNetwork:
