script-opts=ytdl_hook-ytdl_path=yt-dlp
# Allow playing of playlists
ytdl-raw-options=yes-playlist= 

ytdl-format=(bestvideo[vcodec^=av01]/bestvideo)+bestaudio/best
# ytdl-format=mp4[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best


# script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
# ytdl-format=mp4[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best
# ytdl-format=bestvideo[protocol^=m3u8]+bestaudio[protocol^=m3u8]/bestvideo+bestaudio/best # Breaks seeking to non-cached timestamps
# # cache=yes
# # cache-secs=3600
# # demuxer-thread=true
# # demuxer-readahead-secs=3600
# # demuxer-max-bytes=500000KiB // Cache infinitely large junk
# # demuxer-max-back-bytes=500000KiB
