#!/bin/bash

# Fetch data
status="$( acpi | grep -oP 'Battery 0:.*?\K\w+' )"
percentage="$( acpi | grep -oP 'Battery 0:.*?\K[0-9]+' )"
time="$( acpi | grep -oP 'Battery 0:.*?\K\d\d:\d\d+' )"

# If time is not defined
if [[ -z "$time" ]]
then
    time="__:__"
fi

# ACPI is sometimes buggy  when battery is closed to full
# Set battery to be full when charging and at 99%
if [[ "$percentage" -ge 99 && "$status" != "Discharging" ]]
then
    status="Full"
    percentage=100
fi

# Battery is sometimes full, but percentage not 100
if [[ "$status" = "Full" && "$percentage" != "100" ]]
then
    percentage=100
fi

# Prepare out string
out="$percentage%"

case "$status" in
    Charging)
        out="$out -$time"
        ;;
    Discharging)
        out="$out +$time"
        ;;
    Full)
        out="$out"
        ;;
    Unknown)
        out="$out $time"
        ;;
    *)
        out="$out $status"
        ;;
esac

echo "$out"
