# Allow reloading of config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on

# Use vim like bindings for copy
set -g mode-keys vi

# Use  vim keybindings to navigate
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# Move windows to the left and right
bind-key H swap-window -t -1
bind-key L swap-window -t +1

# Increase scroll back history
set-option -g history-limit 50000

# Split panes as in vim using v and s and open in current directory
unbind '"'
unbind '%'
bind s split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

# Color
# set-option -g pane-active-border-style fg=blue
# set -g window-style 'fg=colour0,bg=color2'

## Panes
set -g pane-border-style 'fg=color12'
set -g pane-active-border-style 'fg=color3'

## Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '#(hostname)'
set -g status-right-length 50

setw -g window-status-current-format ' #I #W #F '
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '


## Plugins
# Tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Pane switching is as split switching in vim
set -g @plugin 'christoomey/vim-tmux-navigator'

# Proper support of colors
# Goal: Script produces smooth color transition: https://gist.githubusercontent.com/lifepillar/09a44b8cf0f9397465614e622979107f/raw/24-bit-color.sh
set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
run '/usr/share/tmux-plugin-manager/tpm'
