#!/bin/bash

# $1 corresponts to +, - or m sign
if [[ $1 = "+" ]]
then
    /usr/bin/volume.sh -n -i
elif [[ $1 = "-" ]]
then
    /usr/bin/volume.sh -n -d
elif [[ $1 = "m" ]]
then
    /usr/bin/volume.sh -n -m
fi
